# fly.toml app configuration file generated for uniaodecontbot
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "uniaodecontbot"
primary_region = "gru"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "5000"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"